/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kevsoft_imagecompare_PdiffImageCompare */

#ifndef _Included_org_kevsoft_imagecompare_PdiffImageCompare
#define _Included_org_kevsoft_imagecompare_PdiffImageCompare
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kevsoft_imagecompare_PdiffImageCompare
 * Method:    nativeCompareFailedPixels
 * Signature: ([BII[BII)I
 */
JNIEXPORT jint JNICALL Java_org_kevsoft_imagecompare_PdiffImageCompare_nativeCompareFailedPixels
  (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     org_kevsoft_imagecompare_PdiffImageCompare
 * Method:    nativeCompareFailedPixelsMultiple
 * Signature: ([Lorg/kevsoft/imagecompare/PdiffImageCompare;ILjava/util/HashMap;)V
 */
JNIEXPORT void JNICALL Java_org_kevsoft_imagecompare_PdiffImageCompare_nativeCompareFailedPixelsMultiple
  (JNIEnv *, jclass, jobjectArray, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
